spring:
  liquibase:
    change-log: classpath:/migration/master-changelog.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/item3
    username: postgres
    password: linh2002
  application:
    name: item-service
  spring:
    servlet:
      multipart:
        max-file-size: 30MB
        max-request-size: 30MB
image:
  value: ${path.image}
