spring:
  liquibase:
    change-log: classpath:/migration/master-changelog.xml
  datasource:
    url: jdbc:postgresql://localhost:5432/2
    username: postgres
    password: 123456
  application:
    name: item-service
server:
  port: 8100
